services:
  product-service:
    image: andr72/product-service:v0.0.1
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017/product-service?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0.5
    container_name: product-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - mongo_data_prod:/data/db

volumes:
  mongo_data_prod:
